name: mlp-classifier
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch
  - scikit-learn
  - numpy
  - pip:
    - mlflow==2.7.1
    - flask==2.3.2
    - pyyaml==6.0
    - tqdm==4.65.0
    - gradio==3.35.1 